export const CREATE_USER = 'CREATE_USER';
export const CREATE_USER_ERROR = 'CREATE_USER_ERROR';
export const DELETE_USER = 'DELETE_USER';
export const DELETE_USER_ERROR = 'DELETE_USER_ERROR';
export const SET_USERS = 'SET_USERS';
export const SET_USERS_ERROR = 'SET_USERS_ERROR';